CC = gcc

CFLAGS = -Wall -Wextra -O2

all: 1.exe 2.exe 3.exe 4_1.exe 4_2.exe 5.exe 6.exe 7.exe 8.exe 9.exe 10.exe

1.exe: 1.c
	$(CC) $(CFLAGS) -o $@ $<

2.exe: 2.c
	$(CC) $(CFLAGS) -o $@ $<

3.exe: 3.c
	$(CC) $(CFLAGS) -o $@ $<

4_1.exe: 4_1.c
	$(CC) $(CFLAGS) -o $@ $<

4_2.exe: 4_2.c
	$(CC) $(CFLAGS) -o $@ $<

5.exe: 5.c
	$(CC) $(CFLAGS) -o $@ $<

6.exe: 6.c
	$(CC) $(CFLAGS) -o $@ $<

7.exe: 7.c
	$(CC) $(CFLAGS) -o $@ $<

8.exe: 8.c
	$(CC) $(CFLAGS) -o $@ $<

9.exe: 9.c
	$(CC) $(CFLAGS) -o $@ $<

10.exe: 10.c
	$(CC) $(CFLAGS) -o $@ $<

clean:
	del /Q *.exe
